version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase  # Замените "mydatabase" на имя вашей базы данных
      POSTGRES_USER: admin      # Замените "admin" на имя пользователя базы данных
      POSTGRES_PASSWORD: 88888888  # Замените "88888888" на пароль пользователя базы данных
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
