SELECT c.NAME AS NAME,
       EXTRACT(MONTH FROM AGE(p.FINISH_DATE, p.START_DATE)) AS MONTH_COUNT
FROM project p
JOIN client c ON p.CLIENT_ID = c.ID
JOIN (
    SELECT ID
    FROM project
    ORDER BY EXTRACT(MONTH FROM AGE(FINISH_DATE, START_DATE)) DESC
    LIMIT 1
) max_project ON p.ID = max_project.ID;
